config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root "sessions#new"

  resources :sessions, only: %i[create]
  resources :projects do
    resources :comments, only: %i[new create destroy index]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :author, class_name: "User"

  validates :content, presence: true

  scope :order_by_latest, -> { order(created_at: :desc) }
end

app/models/concerns/email_validator.rb
# frozen_string_literal: true

module EmailValidator
  extend ActiveSupport::Concern

  included do
    validates :email, format: { with: /\A.+@.+\.\w{2,6}\Z/, message: I18n.t("errors.messages.invalid_email") },
                      if: :email_required?

    private

    def email_required?
      email.present?
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :comments, dependent: :destroy_async

  enum status: { active: "active", archived: "archived" }

  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: statuses.keys }

  scope :order_by_latest, -> { order(created_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include EmailValidator

  has_secure_password

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 8, maximum: 16, too_short: I18n.t("errors.messages.password_too_short"),
                                 too_long: I18n.t("errors.messages.password_too_long") }, if: :password_required?
  validates_presence_of :password_confirmation, if: :password_digest_changed?

  has_many :projects, dependent: :destroy_async, foreign_key: :owner_id
  has_many :comments, dependent: :destroy_async, foreign_key: :author_id

  def self.find_authenticated(args = {})
    user = find_by(email: args[:email])
    user if user&.authenticate(args[:password])
  end

  private

  def password_required?
    password.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

require "will_paginate/array"

class ApplicationController < ActionController::Base
  include Pagination
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  protect_from_forgery prepend: true, with: :exception

  before_action :authorize

  protected

  def authorize
    unless session_valid?
      return render json: { errors: [ I18n.t("errors.messages.unauthorized") ] }, status: :unauthorized
    end

    result = Auth::AuthenticateRequestService.call(auth_header: auth_token)
    unless result.success?
      return render json: { errors: [ I18n.t("errors.messages.unauthorized") ] }, status: :unauthorized
    end

    @current_user = result.current_user
  end

  def session_valid?
    auth_token.present?
  end

  def auth_token
    session[:auth_token]
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_project, only: %i[new index destroy]

  # GET /projects/:project_id/comments/new
  def new
    @comment = Comment.new
  end

  # Delete /projects/:project_id/comments/:id
  def destroy
    @comment = @project.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to "/projects/#{params[:project_id]}", notice: I8n.t("comments.destroy.success") }
    end
  end

  # GET /projects/:project_id/comments
  def index
    @comments = @project.comments.all.paginate(page: page_no, per_page: per_page)
  end

  # POST /projects/:project_id/comments
  def create
    result = Comments::CreateService.call(params: comment_params.merge(project_id: params[:project_id]), user: @current_user)
    respond_to do |format|
      if result.success?
        format.html { redirect_to "/projects/#{params[:project_id]}", notice: I18n.t("comments.create.success") }
      else
        format.html { render :new, status: :unprocessable_entity, alert: result.errors }
      end
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/concerns/pagination.rb
# frozen_string_literal: true

module Pagination
  extend ActiveSupport::Concern

  def default_per_page
    10
  end

  def page_no
    params[:page]&.to_i || 1
  end

  def per_page
    params[:per_page]&.to_i || default_per_page
  end

  def paginate_offset
    (page_no-1)*per_page
  end

  def paginate
    ->(it) { it.limit(per_page).offset(paginate_offset) }
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/:id
  def show
    @comments = @project.comments.order_by_latest.includes(:author).paginate(page: page_no, per_page: per_page)
  end

  # GET /projects/:id/edit
  def edit; end

  # GET /projects
  def index
    @projects = Project.includes(:owner).paginate(page: page_no, per_page: per_page)
  end

  # POST /projects
  def create
    result = Projects::CreateService.call(params: project_params, user: @current_user)
    respond_to do |format|
      if result.success?
        format.html { redirect_to "/projects", notice: I18n.t("projects.create.success") }
      else
        format.html { render :new, status: :unprocessable_entity, alert: result.errors }
      end
    end
  end

  # PATCH/PUT /projects/:id
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to "/projects", notice: I18n.t("projects.update.success") }
      else
        format.html { render :edit, status: :unprocessable_entity, alert: @project.errors.full_messages.join(", ") }
      end
    end
  end

  # DELETE /projects/:id
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to "/projects", notice: I18n.t("projects.destroy.success") }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def authorize_user!
    unless @project.owner.id == @current_user.id
      respond_to do |format|
        format.html do
          redirect_to "/projects", alert: I18n.t("projects.unauthorized")
        end
      end
      return false
    end

    true
  end

  def project_params
    params.require(:project).permit(:name, :description, :status)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorize, only: %i[new create]

  # GET /sessions/new
  def new; end

  # POST /sessions
  def create
    result = Auth::LoginService.call(email: login_params[:email], password: login_params[:password])
    if result.success?
      session[:auth_token] = result.token
      redirect_to "/projects"
    else
      flash[:notice] = I18n.t("errors.messages.wrong_email_or_password")
      redirect_to "/"
    end
  end

  private

  def login_params
    params.permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/comments/_comment.html.slim
tr
  td
    = comment.content
  td
    = comment.author_id
  td
    = comment.created_at
  td
    div class="w-full flex flex-row"
      = button_to "Delete", comment_path(comment), method: :delete, \
        data: { turbo_confirm: "Are you sure you want to delete this user?", turbo_frame: "_top" }, \
        class: "mt-2 ml-2 border border-red-500 bg-red-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-red-600 focus:outline-none focus:shadow-outline"

app/views/comments/_form.html.slim
= form_with(model: @comment, url: [@project, @comment]) do |form|
  - if @comment&.errors&.any?
    div style="color: red"
      h2 = "Can't save this comment due to #{pluralize(@comment.errors.count, "error")}"
      ul
        - @comment&.errors.each do |error|
          li = error.full_message

  div
    = form.label :content, style: "display: block"
    = form.text_field :content

  = button_tag "Save", class: "ml-2 border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-green-600 focus:outline-none focus:shadow-outline"
  = link_to "Cancel", projects_path, class: "border border-gray-500 bg-gray-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-gray-600 focus:outline-none focus:shadow-outline"

app/views/comments/new.html.slim
.row
  .col-md-6.mt-4
    = render partial: "shared/flash"
    = render partial: "comments/form"

app/views/layouts/_flash.html.slim
- if notice
  div class="notice mb-4 border border-green-500 bg-green-200 text-green-700 rounded-md px-6 py-2"
    = notice
- if alert
  div class="alert mb-4 border border-red-500 bg-red-200 text-red-700 rounded-md px-6 py-2"
    = alert

app/views/layouts/_navbar.html.slim
div class="w-full bg-blue-600 text-white py-6 flex px-8 justify-between"
  p class="text-bold w-fit" Project Conversation History
  div class="flex-row w-fit"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversationHistory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="p-8">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.slim
= form_with(model: @project)do |form|
  - if @project&.errors&.any?
    div style="color: red"
      h2 = "Can't save this project due to #{pluralize(@project.errors.count, "error")}"
      ul
        - @project&.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :description, style: "display: block"
    = form.text_field :description

  div
    = form.label :status, style: "display: block"
    = form.select :status, Project.statuses.keys

  = button_tag "Save", class: "ml-2 border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-green-600 focus:outline-none focus:shadow-outline"
  = link_to "Cancel", projects_path, class: "border border-gray-500 bg-gray-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-gray-600 focus:outline-none focus:shadow-outline"

app/views/projects/_project.slim
tr
  td
    = link_to project.name, project, data: { turbo_frame: "_top" }, class: "text-xl font-bold text-blue-500 hover:text-blue-600", style: "display: flex; align-items: center; justify-content: center"
  td
    p style="display: flex; align-items: center; justify-content: center" =< project.owner.username
  td
    p style="display: flex; align-items: center; justify-content: center" =< project.description
  td
    p style="display: flex; align-items: center; justify-content: center" =< project.status
  td
    div class="w-full flex flex-row"
      = button_to "Edit", edit_project_path(project), method: :get, class: "mt-2 border border-yellow-500 bg-yellow-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-yellow-600 focus:outline-none focus:shadow-outline"
      = button_to "Delete", project_path(project), method: :delete, \
        data: { turbo_confirm: "Are you sure you want to delete this user?", turbo_frame: "_top" }, \
        class: "mt-2 ml-2 border border-red-500 bg-red-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-red-600 focus:outline-none focus:shadow-outline"

app/views/projects/edit.html.slim
h1 Editing project

= render "form", project: @project

br

div
  => link_to "Show this project", @project
  '|
  =< link_to "Back to projects", projects_path

app/views/projects/index.html.slim
div class="flex justify-between"
  h1 class="mt-6 text-xl font-bold" Projects
  = link_to "New Project", new_project_path, data: { turbo_frame: dom_id(Project.new) }, class: "mt-2 border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-green-600 focus:outline-none focus:shadow-outline"
div class="w-full border-2 border-blue-600 my-4"

h1 class="mt-6 text-xl font-bold mb-4" All Projects
div class="w-full border-2 border-blue-600 my-4"


div class="mt-6"
  table class="w-full"
    thead
      tr
        th Name
        th author
        th Description
        th Status
    tbody
      - @projects.each do |project|
        = render partial: "projects/project", locals: { project: project }

  = will_paginate @projects

app/views/projects/new.html.slim
.row
  .col-md-6.mt-4
    = render partial: "shared/flash"
    = render partial: "form"

app/views/projects/show.html.slim
div class="flex justify-between"
  =< link_to "<- Back to projects", projects_path, class: "hover:underline hover:text-gray-600"
  = link_to "New comment", "#{@project.id}/comments/new", data: { turbo_frame: dom_id(Comment.new) }, class: "mt-2 border border-green-500 bg-green-500 text-white rounded-md px-4 py-2 transition duration-500 ease select-none hover:bg-green-600 focus:outline-none focus:shadow-outline"

div class="w-full flex" style="flex-direction: column"
  div class="flex mt-8" style="flex-direction: row"
    div class="font-bold" style="margin-right: 100px" Name
    h1 =< @project.name

  div class="flex flex-row mt-6" style="flex-direction: row"
    div class="font-bold" style="margin-right: 90px" Owner
    p =< @project.owner.username
 
  div class="flex flex-row mt-6" style="flex-direction: row"
    div class="font-bold" style="margin-right: 50px" Description
    p =< @project.description
 
  div class="flex flex-row mt-6"style="flex-direction: row"
    div class="font-bold" style="margin-right: 90px" Status
    p =< @project.status

- if @project.comments.size > 0
  hr class="h-px my-8 bg-gray-200 border-2 dark:bg-gray-500 mt-4"
  div class="mt-8 text-xl font-bold" Comments
 
  div class="w-full flex" style="flex-direction: column"
    - @comments.each do |comment|
      div class="w-full flex mt-6" style="flex-direction: column"
        div class="flex mb-4" style="flex-direction: row"
          div class="font-bold" style="margin-right: 50px" Author
          p =< comment.author.username
        div class="flex mb-4" style="flex-direction: row"
          div class="font-bold" style="margin-right: 40px" Content
          p =< comment.content
        div class="flex mb-4" style="flex-direction: row"
          div class="font-bold" style="margin-right: 20px" Created at
          p =< comment.created_at
        hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700"

    = will_paginate @comments

app/views/shared/_flash.html.slim
- flash.each do |type, msg|
  .mb-5
    = msg

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  a.navbar-brand.px-3[href="#"]
    | Welcome 
    = @current_user[:name]
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      a.nav-item.nav-link[href="/transactions"]
        | Transactions
      - if @user_type == 'admin'
        li.nav-item
          a.nav-link[href="/merchants"]
            | Merchants